#!/bin/zsh
# Export current terminal configuration to this repository

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${0}")" && pwd)"
cd "$SCRIPT_DIR"

HOSTNAME=$(hostname -s)
USERNAME=$(whoami)
DATE=$(date +"%Y-%m-%d %H:%M")

# Claude Code config dirs — override via env if your layout differs.
# Not derived from $CLAUDE_CONFIG_DIR on purpose: that var is session-contextual
# (the claudep alias flips it), so it can't be trusted to name the work dir.
CLAUDE_DIR="${CLAUDE_DIR:-$HOME/.claude}"
CLAUDE_PERSONAL_DIR="${CLAUDE_PERSONAL_DIR:-$HOME/.claude-personal}"

# ── Bookkeeping ────────────────────────────────────────────────────────────────
# The closing summary is driven by what was actually written, not by a
# hand-maintained list that drifts from reality.
EXPORTED=()
WARNINGS=()
FAILURES=()

note()    { EXPORTED+=("$1") }
warn()    { WARNINGS+=("$1"); echo "  ! $1" }
fail()    { FAILURES+=("$1"); echo "  ✗ $1" }

# Copy via a temp file so an interrupted run can't leave a tracked file truncated.
copy_atomic() {
    cp "$1" "$2.tmp" && mv "$2.tmp" "$2"
}

echo "=== Exporting dev environment configuration ==="
echo ""
echo "Computer: $HOSTNAME"
echo "User: $USERNAME"
echo ""
echo "This will export your ~/.zshrc, ~/.p10k.zsh, tmux config, iTerm2 profiles and app-level"
echo "settings, Phoenix + Karabiner configs, and Claude Code settings to this repository."
echo ""
echo "Files in this repo that may be overwritten:"
echo "  - $SCRIPT_DIR/.zshrc.base, .zshrc.loader, and this machine's .zshrc.c1|c2"
echo "  - $SCRIPT_DIR/.p10k.zsh"
echo "  - $SCRIPT_DIR/plugins.list"
echo "  - $SCRIPT_DIR/brew-packages.list  (static list, rewritten — not scanned)"
echo "  - $SCRIPT_DIR/iterm-profiles/*.json"
echo "  - $SCRIPT_DIR/iterm-settings.json"
echo "  - $SCRIPT_DIR/.phoenix.js"
echo "  - $SCRIPT_DIR/karabiner/karabiner.json"
echo "  - $SCRIPT_DIR/tmux/c1.conf or c2.conf (based on hostname)"
echo "  - $SCRIPT_DIR/bin/tgo, bin/tmux-start"
echo "  - $SCRIPT_DIR/agents/claude/settings.json, agents/claude-personal/settings.json"
echo ""
echo "Your actual config files will NOT be modified."
echo ""
read "REPLY?Continue? (y/N) "
REPLY=${REPLY:-N}
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Export cancelled."
    exit 0
fi
echo ""

# ── Validate sources BEFORE destroying anything ────────────────────────────────
# The cleanup below removes the repo's only copy of .zshrc.full. Validating first
# means a missing source aborts with the repo intact.
echo "✓ Validating sources"
MISSING=()
[ -f ~/.zshrc ]    || MISSING+=("~/.zshrc")
[ -f ~/.p10k.zsh ] || MISSING+=("~/.p10k.zsh")

if (( ${#MISSING[@]} > 0 )); then
    echo ""
    echo "✗ Required source files not found:"
    for m in "${MISSING[@]}"; do echo "    $m"; done
    echo ""
    echo "Aborting — nothing in the repo was modified."
    exit 1
fi
echo ""

# Detect this machine → zsh split label (c1 = Office, c2 = Home).
# LocalHostName, not `hostname -s`: the latter can resolve to a DHCP name (e.g. "192")
# on some LANs, which would misroute the per-machine file.
ZSH_LABEL=""
case "$(scutil --get LocalHostName 2>/dev/null || hostname -s)" in
    mert-cypher-m3max) ZSH_LABEL="c1" ;;
    mrtysn-mbp-m2max)  ZSH_LABEL="c2" ;;
esac

# Export zsh config — split layout: shared base + per-machine file + loader.
# Only THIS machine's .zshrc.<label> is written; the other machine's file is left
# untouched. That one-sided write is what makes repo→machine imports non-destructive.
echo "✓ Exporting zsh configuration"
if [ -f ~/.zshrc.base ]; then
    copy_atomic ~/.zshrc.base .zshrc.base
    note ".zshrc.base"
    copy_atomic ~/.zshrc .zshrc.loader
    note ".zshrc.loader"
    if [[ -n "$ZSH_LABEL" ]] && [ -f ~/.zshrc.$ZSH_LABEL ]; then
        copy_atomic ~/.zshrc.$ZSH_LABEL .zshrc.$ZSH_LABEL
        note ".zshrc.$ZSH_LABEL"

        # Generated, read-only full view (base + THIS machine's block) for reading/
        # diffing. import.sh never reads it, so it cannot clobber real config. Each
        # machine refreshes only its own .combined.<label>, so both stay visible.
        {
            echo "# ─── GENERATED by export.sh — DO NOT EDIT ───────────────────────────────────────"
            echo "# Full assembled ~/.zshrc for '$ZSH_LABEL' = .zshrc.base + .zshrc.$ZSH_LABEL."
            echo "# For reading/diffing only. Source of truth is those two files; import.sh"
            echo "# ignores this. Refreshed whenever export.sh runs on this machine."
            echo "# ────────────────────────────────────────────────────────────────────────────────"
            echo ""
            cat ~/.zshrc.base
            echo ""
            cat ~/.zshrc.$ZSH_LABEL
        } > .zshrc.combined.$ZSH_LABEL.tmp && mv .zshrc.combined.$ZSH_LABEL.tmp .zshrc.combined.$ZSH_LABEL
        note ".zshrc.combined.$ZSH_LABEL (generated, read-only)"
    else
        warn "No ~/.zshrc.$ZSH_LABEL for this machine (label='${ZSH_LABEL:-unknown}') — per-machine file not exported"
    fi
    # Drop the deprecated monolith so it can't shadow the split layout on import.
    [ -f .zshrc.full ] && { rm -f .zshrc.full; echo "  Removed deprecated .zshrc.full"; }
else
    # Legacy fallback: this machine hasn't migrated to the split layout yet.
    warn "~/.zshrc.base not found — exporting monolithic ~/.zshrc to .zshrc.full (legacy)"
    copy_atomic ~/.zshrc .zshrc.full
    note ".zshrc.full (legacy)"
fi

# Export .p10k.zsh
echo "✓ Exporting ~/.p10k.zsh"
copy_atomic ~/.p10k.zsh .p10k.zsh
note ".p10k.zsh"

# Export custom plugin list
echo "✓ Scanning custom plugins"
if [ -d ~/.oh-my-zsh/custom/plugins ]; then
    # (N/) = nullglob + directories only; (:t) takes the basename — no forks, no temp file.
    plugin_dirs=(~/.oh-my-zsh/custom/plugins/*(N/))
    plugin_names=(${plugin_dirs:t})
    plugin_names=(${plugin_names:#example})

    print -l -- ${plugin_names:-} > plugins.list.tmp
    mv plugins.list.tmp plugins.list
    echo "  Found ${#plugin_names[@]} custom plugins"
else
    echo "  No custom plugins directory found"
    : > plugins.list
fi
note "plugins.list"

# Write brew package dependencies (static list, not scanned from system)
# These are packages required by the dev environment:
#   powerlevel10k - prompt theme (sourced in zshrc)
#   fzf           - fuzzy finder (fzf --zsh integration + fzf-tab plugin)
#   asdf          - version manager (paths, commands, plugin)
#   coreutils     - GNU utilities (gnubin in PATH)
#   tree          - directory tree (used by ls plugin)
#   tmux          - terminal multiplexer
echo "✓ Writing brew package dependencies (static list, not scanned)"
cat > brew-packages.list.tmp << 'EOF'
powerlevel10k
fzf
asdf
coreutils
tree
tmux
EOF
mv brew-packages.list.tmp brew-packages.list
note "brew-packages.list (static)"

# Export tmux config
echo "✓ Exporting tmux configuration"
TMUX_TARGET=""

case "$HOSTNAME" in
    mert-cypher-m3max) TMUX_TARGET="tmux/c1.conf"; echo "  Detected: C1 (Office)" ;;
    mrtysn-mbp-m2max)  TMUX_TARGET="tmux/c2.conf"; echo "  Detected: C2 (Home)"   ;;
    *) warn "Unknown hostname: $HOSTNAME, skipping tmux config export" ;;
esac

if [[ -n "$TMUX_TARGET" ]]; then
    mkdir -p tmux bin

    if [ -f ~/.tmux.conf ]; then
        # Resolve symlink to get actual content
        cp -L ~/.tmux.conf "$TMUX_TARGET.tmp" && mv "$TMUX_TARGET.tmp" "$TMUX_TARGET"
        echo "  Exported ~/.tmux.conf → $TMUX_TARGET"
        note "$TMUX_TARGET"
    else
        warn "~/.tmux.conf not found, skipping"
    fi

    for tool in tgo tmux-start; do
        if [ -f ~/bin/$tool ]; then
            copy_atomic ~/bin/$tool "bin/$tool"
            chmod +x "bin/$tool"
            echo "  Exported ~/bin/$tool"
            note "bin/$tool"
        else
            warn "~/bin/$tool not found, skipping"
        fi
    done
fi

# ── iTerm2: profiles AND app-level settings ────────────────────────────────────
# Profiles alone are not enough to reproduce the setup: theme, tab bar geometry,
# the Minimal-theme tuning knobs, global keymaps and pointer actions all live as
# TOP-LEVEL plist keys outside any profile.
#
# Keys are copied verbatim from the live plist and never hand-typed: iTerm reads
# CamelCase names (MinimalDeslectedColoredTabAlpha) while its internal symbols are
# lowercase-first, so a hand-written key list silently produces keys nothing reads.
#
# This repo is PUBLIC. The export applies a denylist for machine-local state and a
# secrets gate that withholds (and reports) anything credential-shaped.
echo "✓ Exporting iTerm2 profiles and settings"
mkdir -p iterm-profiles

ITERM_PLIST="$HOME/Library/Preferences/com.googlecode.iterm2.plist"

if [ ! -f "$ITERM_PLIST" ]; then
    warn "iTerm2 not installed, skipping profiles and settings"
elif ! defaults read com.googlecode.iterm2 &>/dev/null; then
    warn "iTerm2 preferences not readable, skipping profiles and settings"
elif python3 << 'PYTHON_EOF'
import base64
import json
import os
import plistlib
import re
import sys

plist_path = os.path.expanduser("~/Library/Preferences/com.googlecode.iterm2.plist")
profiles_dir = "iterm-profiles"
settings_path = "iterm-settings.json"

# Machine-local / volatile state that must never reach the repo.
# Spaces are written as [ ] — a trailing "\ " before a newline escapes the newline
# in re.VERBOSE, which silently disables the pattern.
DENY = re.compile(r"""^(
      NoSync
    | NSWindow[ ]Frame[ ]
    | NSSplitView[ ]
    | NSToolbar[ ]
    | SU[A-Z]
    | NSNavLastRootDirectory$
    | NSNavPanelExpandedSize
    | NeverWarnAboutShortLivedSessions_
    | findMode_iTerm$
    | kCPK
    | iTerm\ Version$
    | New\ Bookmarks$
    | Bookmarks$
)""", re.VERBOSE)

# The repo is public. Anything credential-shaped is withheld and reported.
# "token" is only credential-shaped when qualified — a bare match also hits
# AiMaxTokens / AiResponseMaxTokens, which are integer limits, not secrets.
SECRET = re.compile(
    r"secret|password|passphrase|credential|api[-_]?key"
    r"|(access|refresh|auth|bearer|session|id)[-_]?token"
    r"|oauth|bearer",
    re.I,
)


def convert_for_json(obj):
    if isinstance(obj, bytes):
        return {"_type": "data", "value": base64.b64encode(obj).decode("ascii")}
    elif isinstance(obj, dict):
        return {k: convert_for_json(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [convert_for_json(item) for item in obj]
    else:
        return obj


def looks_secret(key, value):
    if SECRET.search(key):
        return True
    if isinstance(value, str) and SECRET.search(value):
        return True
    return False


def name_to_filename(name):
    return name.lower().replace(" ", "-") + ".json"


def write_json_atomic(path, payload):
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        json.dump(payload, f, indent=2, sort_keys=True)
    os.replace(tmp, path)


try:
    with open(plist_path, "rb") as f:
        data = plistlib.load(f)
except Exception as e:
    print(f"  Could not read iTerm2 plist: {e}", file=sys.stderr)
    sys.exit(1)

failed = False

# ── profiles ───────────────────────────────────────────────────────────────────
profiles = data.get("New Bookmarks", [])
if not profiles:
    print("  No profiles found in iTerm2")
else:
    exported = 0
    seen = {}
    for profile in profiles:
        name = profile.get("Name", "Unknown")
        filename = name_to_filename(name)

        # Distinct profile names can collapse to one filename (lowercase + hyphenate).
        # Silently overwriting would lose a profile, so refuse and report.
        if filename in seen:
            print(f"  ! Filename collision: '{name}' and '{seen[filename]}' both map to "
                  f"{filename} — skipping '{name}'", file=sys.stderr)
            failed = True
            continue
        seen[filename] = name

        try:
            write_json_atomic(os.path.join(profiles_dir, filename),
                              {"Profiles": [convert_for_json(profile)]})
            print(f"  - {name} -> {filename}")
            exported += 1
        except Exception as e:
            print(f"  Failed to write {filename}: {e}", file=sys.stderr)
            failed = True
    print(f"  Exported {exported} profiles")

# ── app-level settings ─────────────────────────────────────────────────────────
settings, withheld, dropped = {}, [], 0
for key, value in data.items():
    if DENY.search(key):
        dropped += 1
        continue
    if looks_secret(key, value):
        withheld.append(key)
        continue
    settings[key] = convert_for_json(value)

try:
    write_json_atomic(settings_path, {
        "_comment": (
            "iTerm2 app-level preferences (top-level plist keys, excluding profiles). "
            "Keys are copied verbatim — iTerm reads CamelCase names, so casing matters. "
            "Applied by import.sh while iTerm2 is NOT running."
        ),
        "settings": settings,
    })
    print(f"  Exported {len(settings)} app-level settings ({dropped} machine-local keys dropped)")
except Exception as e:
    print(f"  Failed to write {settings_path}: {e}", file=sys.stderr)
    failed = True

if withheld:
    print(f"  ! WITHHELD {len(withheld)} credential-shaped keys (repo is public): "
          + ", ".join(withheld), file=sys.stderr)

sys.exit(1 if failed else 0)
PYTHON_EOF
then
    note "iterm-profiles/*.json"
    note "iterm-settings.json"
else
    fail "iTerm2 export failed — profiles and settings may be stale or incomplete"
fi

# Create font-only profile if it doesn't exist
if [ ! -f iterm-profiles/font-only.json ]; then
    echo "✓ Creating font-only profile template"
    cat > iterm-profiles/font-only.json.tmp << 'EOF'
{
  "Profiles": [
    {
      "Name": "Dev Config (Font Only)",
      "Guid": "DEV-CONFIG-FONT-ONLY-0001",
      "Dynamic Profile Parent Name": "Default",
      "Normal Font": "FiraCodeNFM-Reg 12",
      "Use Non-ASCII Font": false
    }
  ]
}
EOF
    mv iterm-profiles/font-only.json.tmp iterm-profiles/font-only.json
    note "iterm-profiles/font-only.json"
fi

# Export window & keyboard configs (Phoenix window manager, Karabiner keymaps)
# Both are portable, non-secret text — safe for this public repo.
echo "✓ Exporting window & keyboard configs"

if [ -f ~/.phoenix.js ]; then
    copy_atomic ~/.phoenix.js .phoenix.js
    echo "  Exported ~/.phoenix.js"
    note ".phoenix.js"
else
    warn "~/.phoenix.js not found, skipping"
fi

# Karabiner: only karabiner.json — never assets/ or automatic_backups/ (churny local state).
if [ -f ~/.config/karabiner/karabiner.json ]; then
    mkdir -p karabiner
    copy_atomic ~/.config/karabiner/karabiner.json karabiner/karabiner.json
    echo "  Exported ~/.config/karabiner/karabiner.json"
    note "karabiner/karabiner.json"
else
    warn "~/.config/karabiner/karabiner.json not found, skipping"
fi

# Export Claude Code settings (both config dirs)
# Only settings.json is synced. *.local.json (machine-local) and memory/ (private)
# are deliberately never read here.
echo "✓ Exporting Claude Code settings"

# "<source config dir>:<repo subdir>"  (braces required — bare $VAR:c is a zsh modifier)
AGENTS_DIR="agents"
CLAUDE_PAIRS=(
    "${CLAUDE_DIR}:$AGENTS_DIR/claude"
    "${CLAUDE_PERSONAL_DIR}:$AGENTS_DIR/claude-personal"
)
# Churny state fields stripped on export — they regenerate locally and only add diff noise.
CLAUDE_STRIP_FILTER='del(.feedbackSurveyState)'

for pair in "${CLAUDE_PAIRS[@]}"; do
    src="${pair%%:*}/settings.json"
    repo_sub="${pair##*:}"
    dest="$repo_sub/settings.json"

    if [ ! -f "$src" ]; then
        warn "$src not found, skipping"
        continue
    fi

    mkdir -p "$repo_sub"
    if command -v jq >/dev/null 2>&1 && jq "$CLAUDE_STRIP_FILTER" "$src" > "$dest.tmp" 2>/dev/null; then
        mv "$dest.tmp" "$dest"
        echo "  Exported $src → $dest"
    else
        rm -f "$dest.tmp"
        copy_atomic "$src" "$dest"
        # The raw copy keeps .feedbackSurveyState, which the filter exists to remove.
        warn "jq unavailable or filter failed — copied $src verbatim (churny state NOT stripped)"
    fi
    note "$dest"
done

# Log export to EXPORTS.md
echo "✓ Logging export"
if [ ! -f EXPORTS.md ]; then
    cat > EXPORTS.md << 'EOF'
# Export History

| Date | Computer | User |
|------|----------|------|
EOF
fi

echo "| $DATE | $HOSTNAME | $USERNAME |" >> EXPORTS.md
note "EXPORTS.md (appended)"

echo ""
echo "=== Export complete ==="
echo ""
echo "Files exported:"
for f in "${EXPORTED[@]}"; do echo "  - $SCRIPT_DIR/$f"; done

if (( ${#WARNINGS[@]} > 0 )); then
    echo ""
    echo "Warnings (${#WARNINGS[@]}):"
    for w in "${WARNINGS[@]}"; do echo "  ! $w"; done
fi

if (( ${#FAILURES[@]} > 0 )); then
    echo ""
    echo "Failures (${#FAILURES[@]}):"
    for f in "${FAILURES[@]}"; do echo "  ✗ $f"; done
fi

echo ""
echo "Next steps:"
echo "  1. Review the exported files: git diff"
echo "  2. This repo is PUBLIC — read iterm-settings.json before committing"
echo "  3. Commit and push changes: git add . && git commit && git push"

(( ${#FAILURES[@]} == 0 ))
